language: python
sudo: required

env:
    global:
        # 1. Generated a token for travis at https://anaconda.org/quantopian/settings/access with scope conda.
        # 2. Generated secure env var below with travis gem via
        #     $ travis encrypt ANACONDA_TOKEN=$TOKEN
        secure: JJM9uKCS53Nc7gmrnSDFrBKODeJTLIgqrqawIBiCoelLUQU4G1ppg04MfHPDMDYwVWO1hI266OerfMOKi1ccsOGgEz+h2oX1aWcgN3UkEtX6/NZaDGwxM774bM/6NUqraM0qPaUBfZwQfbBbF6vTtgWntBIyNLMEC1fjT7X5Xazg4nCHo3cXWlsY6gohmayNl7jJBBhZQGw8qDe0Yv8ksDXC7Tx4j2oX7Y6f3d3DREPVGjUt4MMQrYzvDFDbW3WYYM/aR1nm3f7gZMfXWLltOCK1v7DKID4d4IxAgcTYhKi7nIzdozhUSxBAox7Gps2nY6yySbKnC3K18kNsB0TXxotEgsE9UoQiSlRcOnw924cBA1L1D/TIXTOyTlAupwBhlFY5rWig9X2+WDSLC0YL2LbRHl5yTeY75IHxzyLe8QjvOLOTWQTr6flq8acPYCinGGmRRM71jmkofS+mt7ABQauUSrXQ0xo/yJJLo5f99LkMdcUPHl7r6ERo2ZpPOzUD411Cva9qpT8vBOTnrkUwidBC5maSkPq4NGdY4FHdT/mq2h8eaWp7Cgbma+FnpXH3QpU7VOsIK/c6C/ExeR/Of6MgsfdzcjWUQ+yarl7RK37qRW5lYe4UH5R4CasolwIlMgPLXGs139b7ydgzr2FsLKuv+QuB0GRcdp1VFKNxceU=

matrix:
    include:
        - os: osx
          language: generic
          env: TEST_HELP=1
        - os: linux
          sudo: required
          python: 2.7
          env: TEST_FUNCTIONALITY=1
        - os: linux
          sudo: required
          python: 3.5
          env: TEST_FUNCTIONALITY=1 TEST_STYLE=1
        - os: linux
          sudo: required
          python: 3.6
          env: TEST_HELP=1

before_install:
    - ./ci/install_conda.sh

install:
    - ./ci/build_package.sh

script:
    - ./ci/test_package.sh

deploy:
    - provider: script
      skip_cleanup: true
      on:
          repo: Cibiv/UMI-tools
          tags: true
      script: ./ci/deploy_package.sh
