package:
  name: "umi_tools_tuc"
  version: {{ environ.get('BUILD_VERSION', '')|replace("-","_") }}

source:
  git_url: ../
  git_rev: HEAD

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - matplotlib
    - scipy
    - regex
    - freetype
    - certifi ==2016.9.26
    - setuptools >=1.1
    - cython >=0.19
    - numpy >=1.7
    - pandas >=0.12.0
    - pysam >=0.8.4
    - future
  run:
    - python {{ python }}
    - matplotlib
    - scipy
    - regex
    - freetype
    - certifi ==2016.9.26
    - cython >=0.19
    - numpy >=1.7
    - pandas >=0.12.0
    - pysam >=0.8.4
    - future

test:
  commands:
    - umi_tools --help

about:
  home: https://github.com/fgp/UMI-tools
  license: MIT License
  summary: 'Tools for dealing with Unique Molecular Identifiers
            (UMIs) / Random Molecular Tags (RMTs). This version
            is patched to work together with trumicount. Original
            version can be found at https://github.com/CGATOxford/UMI-tools'
